### ISSUE TITLE
Getting a makefile error when running make in the root directory

### ISSUE THREAD

**Issue by ingmarfjolla** [riscv/sail-riscv#352] opened 2023-11-17 21:32 UTC
Hello, I'm running into this error: 

```
File "generated_definitions/lem/RV64/riscv.lem", line 18571, character 7:
  Syntax error
make: *** [Makefile:330: generated_definitions/isabelle/RV64/Riscv.thy] Error 1
```
when running `make` after cloning this repo. 

I'm using an Ubuntu container, with `opam --version 2.1.2` , `The OCaml toplevel, version 5.1.0` , and `Sail 0.17.1 (sail @ opam-v2.1.2)`. Any help in debugging would be appreciated, not sure if I missed anything else. I have Isabelle and Coq on my path as well. I followed the documentation here: https://github.com/rems-project/sail/blob/sail2/INSTALL.md to install sail and get the other system dependencies mentioned. 

Thank you!

**Comment by ingmarfjolla** [comment] 2023-11-17 21:43
![Screenshot 2023-11-17 at 4 43 28 PM](https://github.com/riscv/sail-riscv/assets/33461904/d7608aa5-f848-4906-b20b-bae0494e2894)
This is what's at line 18,571 , not sure how it differs from the other lines

**Comment by jrtc27** [comment] 2023-11-17 21:47
Duplicate of #325

**Closed by jrtc27** 2023-11-17 21:47 UTC

**Comment by Alasdair** [comment] 2023-11-18 00:42
See https://github.com/riscv/sail-riscv/pull/353 and the comment I made in #325
