### ISSUE TITLE
No CHANGELOG.md file

### ISSUE THREAD

**Issue by allenjbaum** [riscv/sail-riscv#188] opened 2022-10-25 22:21 UTC
We need a CHANGELOG file with a version number so that we can audit and debug test reports

**Comment by jrtc27** [comment] 2022-10-25 22:22
Context? The changelog is called "read git log"...

**Comment by jrtc27** [comment] 2022-10-25 22:24
Though from your _description_ you don't want a changelog, you want a version number, which is a duplicate of #109?

**Comment by allenjbaum** [comment] 2022-10-26 00:19
Ah, yes, thanks, I couldn't a version number, so this is just a duplicate.
In our other repos, it's a line in the changelog, but a --version command is superior to have to parse that.

**Closed** 2022-10-26 00:19 UTC
